site_name: HUIT Open OnDemand User Documentation

nav:
  - Home: index.md
  - File Management: file-management.md
  - Shared Folder: shared-folder.md
  - Terminal App: terminal.md
  - Interactive Apps:
    - Overview: interactive-apps.md
    - Jupyter Lab: jupyterlab-apptainer.md
    - Remote Desktop: remote-desktop-ros.md
    - Code Server: vscode-app.md
  - Software (Spack):
    - Overview / Global: spack-shared-software.md
    - Course level: spack-course-shared.md
    - Personal install: spack-local.md
    - Package management: package-management.md
  - Troubleshooting: troubleshooting.md

theme:
  name: material
  palette:
    scheme: harvard
  logo: assets/harvard_shield.svg
  favicon: assets/favicon.ico

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
