site_name: HUIT Open OnDemand User Documentation

nav:
  - Home: index.md
  - File Management: file-management.md
  - Terminal App: terminal.md
  - Interactive Apps:
    - Overview: interactive-apps.md
    - JupyterLab (Spack): jupyterlab-spack.md
    - Remote Desktop: remote-desktop-ros.md
    - Code Server: vscode-app.md
  - Shared Software: spack-shared-software.md
  - Shared Folder: shared-folder.md
  - Personal Software: spack-local.md
  - Troubleshooting: troubleshooting.md

theme:
  name: material
  palette:
    scheme: harvard
  logo: assets/harvard_shield.svg
  favicon: assets/favicon.ico

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
