site_name: HUIT Open OnDemand User Documentation

nav:
  - Home: index.md
  - File Management: file-management.md
  - Terminal App: terminal.md
  - VS Code App: vscode-app.md
  - Shared Software: spack-shared-software.md
  - Personal Software: spack-local.md

theme:
  name: material
  palette:
    scheme: harvard
  logo: assets/harvard_shield.svg
  favicon: assets/favicon.ico

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
